import {
  formatResourceReference,
  frameworkSecretNameTemplate,
  isResourceReference,
  resolveServiceTarget,
  type FrameworkConfig,
  type NormalizedTarget,
  type ResourceReference,
} from "../src/config/index";

function comment(text: string): string {
  return text.split(/\r?\n/).map((line) => `# ${line}`).join("\n");
}

function sameResource(left: ResourceReference, right: ResourceReference): boolean {
  return left.path.join(".") === right.path.join(".");
}

function requirementsFor(reference: ResourceReference, targets: readonly NormalizedTarget[]): string[] {
  return targets.flatMap((target) => target.cloud.requirements
    .filter((requirement) => requirement.require.some((entry) => sameResource(entry, reference)))
    .map((requirement) => {
      const condition = requirement.when
        ? ` when ${requirement.when.resource.fromEnv ?? formatResourceReference(requirement.when.resource)}=${JSON.stringify(requirement.when.equals)}`
        : "";
      return comment(`Required for deployed ${target.reference}${condition}.`);
    }));
}

/** Documentation only: this file is neither an input file nor copied into a container. */
export function serviceEnvironmentExample(config: FrameworkConfig, target: NormalizedTarget, port: number): string {
  const service = resolveServiceTarget(config, target.id);
  const lines = [
    "# Generated by npm run framework:generate from framework.config.ts. Do not edit.",
    `# Declared environment for ${target.reference} by the framework.`,
    "# Documentation only: do not copy this to a service .env file.",
    "# Set authored inputs in cdk-app/.env, then run npm run export:cdk-outputs and recreate Compose containers.",
    "# Construct attributes are exported into the development resource manifest,",
    "# not into an .env file: npm run export:cdk-outputs writes them there.",
    "",
    "# Declared workload environment (in declaration order):",
  ];
  for (const [name, value] of Object.entries(target.environment)) {
    if (!isResourceReference(value)) {
      lines.push(comment(`${name}: literal ${JSON.stringify(value)}`));
      continue;
    }
    // A construct's attribute is read from the development resource manifest,
    // keyed by reference — not from a root .env variable, which carries Compose
    // controls only.
    const local = value.fromEnv
      ? `${value.fromEnv} in cdk-app/.env${value.default === undefined ? " (optional)" : `; default ${JSON.stringify(value.default)}`}`
      : "the development resource manifest, written by npm run export:cdk-outputs";
    lines.push(comment(`${name}: ${formatResourceReference(value)}; read locally from ${local}.`));
  }
  if (Object.keys(target.secrets).length > 0) {
    lines.push("", "# Startup secrets:");
    for (const [name, entry] of Object.entries(target.secrets)) {
      lines.push(comment(
        entry.fromEnv
          ? `${name}: raw value ${entry.fromEnv} in cdk-app/.env; deployed from the Secrets Manager secret ${frameworkSecretNameTemplate(entry.fromEnv)}, written by npm run deploy.`
          : entry.secretField === undefined
            ? `${name}: ${formatResourceReference(entry)}, a Secrets Manager handle the composition root supplies; absent locally.`
            : `${name}: the ${JSON.stringify(entry.secretField)} key of resources.${entry.path.join(".")}, a Secrets Manager handle the composition root supplies; extracted by ECS at startup and absent locally.`,
      ));
      lines.push(...requirementsFor(entry, [target]));
    }
    lines.push("# Local requirements are checked by the workload at runtime, not by framework preflight.");
  }
  lines.push("", "# Framework-owned environment:", `# PORT: ${port}`, "# AWS_REGION: deployment region in ECS; LOCAL_AWS_REGION in cdk-app/.env for local AWS facilities.");
  if (service.healthCheckPath) lines.push(comment(`HEALTH_CHECK_PATH: ${service.healthCheckPath} (local health probe).`));
  lines.push("# Local facilities, environment mapping and health checks are authored in docker-compose.yml.");
  return `${lines.join("\n")}\n`;
}
