import {
  formatResourceReference,
  frameworkSecretNameTemplate,
  getFrameworkTargets,
  isResourceReference,
  listResourceDeclarations,
  resolveServiceTarget,
  type FrameworkConfig,
  type NormalizedTarget,
  type ResourceReference,
} from "../src/config/index";

export const ENV_EXAMPLES_START = "# BEGIN GENERATED FRAMEWORK INPUTS";
export const ENV_EXAMPLES_END = "# END GENERATED FRAMEWORK INPUTS";

function comment(text: string): string {
  return text.split(/\r?\n/).map((line) => `# ${line}`).join("\n");
}

function sameResource(left: ResourceReference, right: ResourceReference): boolean {
  return left.path.join(".") === right.path.join(".");
}

function requirementsFor(reference: ResourceReference, targets: readonly NormalizedTarget[]): string[] {
  return targets.flatMap((target) => target.cloud.requirements
    .filter((requirement) => requirement.require.some((entry) => sameResource(entry, reference)))
    .map((requirement) => {
      const condition = requirement.when
        ? ` when ${requirement.when.resource.fromEnv ?? formatResourceReference(requirement.when.resource)}=${JSON.stringify(requirement.when.equals)}`
        : "";
      return comment(`Required for deployed ${target.reference}${condition}.`);
    }));
}

/** Which workloads read a secret, so whoever fills it in knows what it is for. */
function readersOf(
  reference: ResourceReference,
  targets: readonly NormalizedTarget[],
): readonly string[] {
  return targets
    .filter(
      (target) =>
        Object.values(target.secrets).some((entry) => sameResource(entry, reference)) ||
        Object.values(target.environment).some(
          (value) => isResourceReference(value) && sameResource(value, reference),
        ),
    )
    .map((target) => target.reference);
}

/** Only declaration metadata is read. Authored env files and secret values never enter generation. */
export function deploymentEnvironmentExample(config: FrameworkConfig): string {
  const targets = getFrameworkTargets(config);
  const lines = [
    ENV_EXAMPLES_START,
    "# Generated by npm run framework:generate from framework.config.ts. Do not edit this block.",
    "# Copy this example to cdk-app/.env for authored cloud and local inputs.",
    "# Cloud reads use the corresponding -c camelCaseName as an override.",
  ];
  // Secrets you author are catalog declarations like any other, so they come
  // out of the same walk. They are collected separately only to be printed
  // under their own heading, which explains where the value goes.
  const secretLines: string[] = [];

  const declarations: { authored: boolean; notes: string[]; path: string; assignments: string[] }[] = [];
  for (const reference of listResourceDeclarations(config.resources ?? {})) {
    if (!reference.fromEnv) continue;
    if (reference.kind === "secret") {
      const readers = readersOf(reference, targets);
      secretLines.push(
        ...(readers.length > 0
          ? [comment(`Read by ${readers.join(", ")}.`)]
          : [comment(`${formatResourceReference(reference)}, read where the stacks are composed.`)]),
        ...(reference.note ? [comment(reference.note)] : []),
        ...requirementsFor(reference, targets),
        `${reference.fromEnv}=`,
      );
      continue;
    }
    const notes: string[] = [];
    if (reference.note) {
      // An authored note is the whole comment: it was written because the
      // derived lines below were not worth their space.
      notes.push(comment(reference.note));
    } else {
      if (reference.values) notes.push(comment(`Allowed values (case-insensitive): ${reference.values.join(", ")}.`));
      if (reference.default === undefined) {
        notes.push("# Optional; leave blank to use the workload's runtime fallback, if any.");
      }
      notes.push(...requirementsFor(reference, targets));
    }
    const value = reference.default ?? "";
    const encoded = value === "" || /^[A-Za-z0-9_./:@+-]+$/.test(value) ? value : JSON.stringify(value);
    const assignments = [`${reference.fromEnv}=${encoded}`];
    declarations.push({
      authored: reference.note !== undefined,
      notes,
      path: comment(formatResourceReference(reference)),
      assignments,
    });
  }

  for (let index = 0; index < declarations.length; index += 1) {
    lines.push("");
    // Authored notes name their own variable, so a run of them is one block.
    if (declarations[index].authored) {
      for (; index < declarations.length && declarations[index].authored; index += 1) {
        lines.push(...declarations[index].notes, ...declarations[index].assignments);
      }
      index -= 1;
      continue;
    }
    // Neighbouring derived notes that read identically are printed once.
    const notes = declarations[index].notes;
    const group = [declarations[index]];
    while (index + 1 < declarations.length && !declarations[index + 1].authored &&
           JSON.stringify(declarations[index + 1].notes) === JSON.stringify(notes)) {
      group.push(declarations[(index += 1)]);
    }
    lines.push(...notes);
    for (const declaration of group) lines.push(declaration.path, ...declaration.assignments);
  }

  if (secretLines.length > 0) {
    lines.push("",
      "# Secrets: the raw value, authored here and nowhere else.",
      "# Compose passes it straight to the container locally. For a deployment,",
      `# npm run deploy copies it into Secrets Manager as ${frameworkSecretNameTemplate()},`,
      "# and only that secret's ARN ever reaches a CloudFormation template.",
      ...secretLines);
  }
  lines.push(ENV_EXAMPLES_END);
  return lines.join("\n");
}

/** Replace just the generated section, retaining authored deployment policy around it. */
export function replaceEnvironmentExampleBlock(previous: string, block: string): string {
  const start = previous.indexOf(ENV_EXAMPLES_START);
  const end = previous.indexOf(ENV_EXAMPLES_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start) ||
      previous.indexOf(ENV_EXAMPLES_START, start + ENV_EXAMPLES_START.length) !== -1 ||
      previous.indexOf(ENV_EXAMPLES_END, end + ENV_EXAMPLES_END.length) !== -1) {
    throw new Error("Environment example has malformed generated framework input markers.");
  }
  if (start === -1) return `${previous.trimEnd()}\n\n${block}\n`;
  return previous.slice(0, start) + block + previous.slice(end + ENV_EXAMPLES_END.length);
}

/** Documentation only: this file is neither an input file nor copied into a container. */
export function serviceEnvironmentExample(config: FrameworkConfig, target: NormalizedTarget, port: number): string {
  const service = resolveServiceTarget(config, target.id);
  const lines = [
    "# Generated by npm run framework:generate from framework.config.ts. Do not edit.",
    `# Declared environment for ${target.reference} by the framework.`,
    "# Documentation only: do not copy this to a service .env file.",
    "# Set authored inputs in cdk-app/.env, then run npm run export:cdk-outputs and recreate Compose containers.",
    "# Construct attributes are exported into the development resource manifest,",
    "# not into an .env file: npm run export:cdk-outputs writes them there.",
    "",
    "# Declared workload environment (in declaration order):",
  ];
  for (const [name, value] of Object.entries(target.environment)) {
    if (!isResourceReference(value)) {
      lines.push(comment(`${name}: literal ${JSON.stringify(value)}`));
      continue;
    }
    // A construct's attribute is read from the development resource manifest,
    // keyed by reference — not from a root .env variable, which carries Compose
    // controls only.
    const local = value.fromEnv
      ? `${value.fromEnv} in cdk-app/.env${value.default === undefined ? " (optional)" : `; default ${JSON.stringify(value.default)}`}`
      : "the development resource manifest, written by npm run export:cdk-outputs";
    lines.push(comment(`${name}: ${formatResourceReference(value)}; read locally from ${local}.`));
  }
  if (Object.keys(target.secrets).length > 0) {
    lines.push("", "# Startup secrets:");
    for (const [name, entry] of Object.entries(target.secrets)) {
      lines.push(comment(
        entry.fromEnv
          ? `${name}: raw value ${entry.fromEnv} in cdk-app/.env; deployed from the Secrets Manager secret ${frameworkSecretNameTemplate(entry.fromEnv)}, written by npm run deploy.`
          : entry.secretField === undefined
            ? `${name}: ${formatResourceReference(entry)}, a Secrets Manager handle the composition root supplies; absent locally.`
            : `${name}: the ${JSON.stringify(entry.secretField)} key of resources.${entry.path.join(".")}, a Secrets Manager handle the composition root supplies; extracted by ECS at startup and absent locally.`,
      ));
      lines.push(...requirementsFor(entry, [target]));
    }
    lines.push("# Local requirements are checked by the workload at runtime, not by framework preflight.");
  }
  lines.push("", "# Framework-owned environment:", `# PORT: ${port}`, "# AWS_REGION: deployment region in ECS; LOCAL_AWS_REGION in cdk-app/.env for local AWS facilities.");
  if (service.healthCheckPath) lines.push(comment(`HEALTH_CHECK_PATH: ${service.healthCheckPath} (local health probe).`));
  lines.push("# Local facilities, environment mapping and health checks are authored in docker-compose.yml.");
  return `${lines.join("\n")}\n`;
}
