import assert from "node:assert/strict";
import test from "node:test";
import { z } from "zod";
import {
  agentCoreModule,
  agentRouteDeclarations,
  assertWorkflowAgentsRespond,
  readAgentContract,
  readToolContract,
} from "../scripts/agentcore-contracts";
import { IDENTITY_ARGUMENT } from "../src/protocol/agentcore";

const echo = {
  description: "Echo a message.",
  request: z.object({ message: z.string().describe("The text") }),
  response: z.object({ message: z.string(), length: z.number().int() }),
};

test("a tool contract becomes the schema Gateway lists and the types agents call it with", async () => {
  const tool = readToolContract({ contract: echo }, { id: "echo", auth: true });
  const source = await agentCoreModule(
    [tool],
    [
      readAgentContract(
        { contract: { request: z.object({ message: z.string() }), event: z.object({ text: z.string() }) } },
        { id: "echo-agent", auth: true, tools: ["echo"] },
      ),
    ],
  );

  assert.match(source, /Generated by npm run framework:generate/);
  assert.match(source, /"echo": \{\n\s+"description": "Echo a message\.",\n\s+"auth": true,/);
  assert.match(source, /"inputSchema": \{\n\s+"type": "object",\n\s+"properties": \{\n\s+"message": \{\n\s+"type": "string",\n\s+"description": "The text\."/);
  assert.match(source, /"echo-agent": \{\n\s+"auth": true,\n\s+"streaming": true,\n\s+"tools": \[\n\s+"echo"\n\s+\]/);
  assert.match(source, /export interface AgentCoreTools \{\n\s+"echo": \{ request: ToolEchoRequest; response: ToolEchoResponse \};/);
  assert.match(source, /export interface AgentCoreAgents \{\n\s+"echo-agent": \{ tools: "echo"; request: AgentEchoAgentRequest; event: AgentEchoAgentEvent \};/);
  assert.match(source, /export interface ToolEchoRequest \{\n\s+\/\*\*\n\s+\* The text\n\s+\*\/\n\s+message: string;\n\}/);
});

test("the browser package learns each agent with users: its route, and the contract it is typed by", () => {
  const generated = agentRouteDeclarations([{ id: "echo-agent", path: "/chat/echo" }]);
  assert.deepEqual(generated.imports, ['import type * as agentEchoAgent from "./contracts/agent-echo-agent";']);
  assert.match(generated.body, /export const AGENT_ROUTE = \{\n  "echo-agent": "\/chat\/echo",\n\} as const;/);
  assert.match(generated.body, /export interface AgentEndpoints \{\n  "echo-agent": typeof agentEchoAgent\.contract;\n\}/);
  assert.deepEqual(agentRouteDeclarations([]).imports, []);
});

test("contracts that cannot work as tools are refused naming the file's export", () => {
  assert.throws(
    () => readToolContract({ contract: { ...echo, description: "" } }, { id: "echo", auth: false }),
    /tools\["echo"\] contract\.description must say what the tool does/,
  );
  assert.throws(
    () =>
      readToolContract(
        { contract: { ...echo, request: z.object({ [IDENTITY_ARGUMENT]: z.string() }) } },
        { id: "echo", auth: false },
      ),
    /tools\["echo"\] contract\.request declares __framework_identity, which the framework reserves/,
  );
  assert.throws(
    () => readToolContract({ contract: { ...echo, request: z.object({ v: z.union([z.string(), z.number()]) }) } }, { id: "echo", auth: false }),
    /tools\["echo"\]\.request\.v: Gateway tool schemas cannot express a union/,
  );
  assert.throws(() => readToolContract({}, { id: "echo", auth: false }), /tools\["echo"\] contract\.ts must export `contract`/);
  assert.throws(
    () => readAgentContract({ contract: { request: z.object({}) } }, { id: "a", auth: false, tools: [] }),
    /agents\["a"\] contract must declare either response or event/,
  );
});

test("a workflow step may name only an agent that answers with one response", () => {
  const respond = readAgentContract(
    { contract: { request: z.object({ caseId: z.string() }), response: z.object({ verdict: z.string() }) } },
    { id: "case-analysis", auth: false, tools: [] },
  );
  const stream = readAgentContract(
    { contract: { request: z.object({ message: z.string() }), event: z.object({ text: z.string() }) } },
    { id: "narrator", auth: false, tools: [] },
  );
  const workflows = (target: string) => [{ origin: 'workflows["review"]', targets: ["lambda:store", target] }];
  assert.doesNotThrow(() => assertWorkflowAgentsRespond(workflows("agent:case-analysis"), [respond, stream]));
  assert.throws(
    () => assertWorkflowAgentsRespond(workflows("agent:narrator"), [respond, stream]),
    /workflows\["review"\] invokeAgent\("narrator"\) calls an agent whose contract streams events/,
  );
});
