/// <reference types="vitest/config" />
import { resolve } from "node:path";

import { defineConfig, loadEnv } from "vite";
import { devtools } from "@tanstack/devtools-vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const config = defineConfig(({ command, mode }) => {
  // This workspace's .env owns the Cognito values; the repository root's is
  // generated by `npm run export:cdk-outputs` and owns VITE_API_GATEWAY_URL,
  // built from LOCAL_API_DEV_SERVER_HOST_PORT in cdk-app/.env. The root
  // is layered second because a hand-written proxy target goes stale the
  // moment that port moves — override the port, or VITE_API_GATEWAY_URL
  // itself, in cdk-app/.env instead.
  const env = {
    ...loadEnv(mode, process.cwd(), ""),
    ...loadEnv(mode, resolve(import.meta.dirname, ".."), ""),
  };
  const apiProxyTarget = env.VITE_API_GATEWAY_URL?.replace(/\/+$/, "");

  // The client always calls a same-origin /api, matching the CloudFront
  // /api/* behavior in a deployed stack. VITE_API_GATEWAY_URL is no longer
  // read by application code -- it is only this proxy's target.
  //
  // Not enforced under `mode === "test"`: Vitest resolves this config with
  // command "serve", and .env is gitignored, so a fresh clone would fail to
  // run its tests for a reason that has nothing to do with them.
  if (command === "serve" && mode !== "test" && !apiProxyTarget) {
    throw new Error(
      "VITE_API_GATEWAY_URL is required as the local /api proxy target. See client-app/.env.example.",
    );
  }

  return {
    base: "/",
    resolve: {
      tsconfigPaths: true,
    },
    server: apiProxyTarget
      ? {
          proxy: {
            "/api": {
              target: apiProxyTarget,
              changeOrigin: true,
              // The lookahead keeps a path like /apifoo from being mangled.
              rewrite: (path) => path.replace(/^\/api(?=\/|$)/, "") || "/",
            },
          },
        }
      : undefined,
    plugins: [
      devtools(),
      tailwindcss(),
      tanstackRouter({
        target: "react",
        autoCodeSplitting: true,
      }),
      viteReact(),
    ],
    test: {
      // Node 25+ defines its own localStorage global, which is undefined without
      // --localstorage-file and hides jsdom's, so every storage-backed test fails.
      execArgv: ["--no-experimental-webstorage"],
    },
  };
});

export default config;
