import {
  StateGraph,
  StateSchema,
  MessagesValue,
  START,
  END,
  MemorySaver,
  Command,
  interrupt,
} from "@langchain/langgraph";
import type { Runtime, StateSnapshot } from "@langchain/langgraph";
import {
  AIMessage,
  HumanMessage,
  SystemMessage,
  ToolMessage,
} from "@langchain/core/messages";
import type { BaseMessage } from "@langchain/core/messages";
import { ToolNode } from "@langchain/langgraph/prebuilt";
import { tool } from "@langchain/core/tools";
import type { ToolRuntime } from "@langchain/core/tools";
import type { AgentTools, ModelToolSpec } from "@repo/framework/runtime/agentcore";
import { z } from "zod";

import { getModel } from "./providers";
import { extractText, toModelMessages } from "./providers/messages";
export { extractText };

/* ============================================================
 * 1. State
 * ------------------------------------------------------------
 * The single object threaded through every node. This is the
 * first thing to extend when the agent needs to remember more
 * than just the conversation. Each field is a schema (zod here,
 * but any "Standard Schema" — valibot, arktype — works) whose
 * `.default(...)` seeds the value for a brand-new thread; once a
 * node writes to it, that value is checkpointed and persists
 * across every later turn on the same thread. Wrap the schema in
 * `ReducedValue`/`DeltaValue` (also from @langchain/langgraph)
 * instead, if a field needs custom merge logic rather than plain
 * overwrite-on-write — that's what `MessagesValue` above already
 * does for `messages` (it appends instead of replacing).
 *
 * `initialInvocation` below is a minimal example: true only until
 * the assistant node has run once on this thread. Read it in any
 * node via `state.initialInvocation`, or in any tool via a second
 * `runtime: ToolRuntime<typeof GraphState.State>` parameter — see
 * `request_human_confirmation` below for that pattern.
 * ============================================================ */

export const GraphState = new StateSchema({
  messages: MessagesValue,
  initialInvocation: z.boolean().default(true),
});
export type GraphStateType = typeof GraphState.State;

/**
 * Per-turn context: what one run of the graph is given and never
 * checkpoints. `tools` is the agent's Gateway for this turn — it
 * carries the turn's abort signal, and the user's token for any
 * tool that acts as the user — so it arrives with each run rather
 * than living in state. Nodes read it as `runtime.context`.
 */
export const GraphContext = z.object({
  tools: z.custom<AgentTools>(),
});
export type GraphContextType = z.infer<typeof GraphContext>;

/* ============================================================
 * 2. Tools
 * ------------------------------------------------------------
 * Anything the assistant is allowed to call. Two kinds:
 *
 * - The graph's own tools, written here. One that has to reach
 *   into the graph itself — interrupt(), state — lives here.
 * - The agent's Gateway tools: Lambdas declared on the agent in
 *   framework-config/agents/example.ts. Give the agent another
 *   one by writing its Lambda and listing it there; it reaches
 *   the model and the shared `tools` node with no change here.
 * ============================================================ */

// Example tool: pauses the graph via interrupt() for human-in-the-loop input.
// The second `runtime` parameter is how a tool reads shared graph state —
// same mechanism as any node, just accessed via `runtime.state` instead of a
// direct `state` argument.
const requestHumanConfirmationTool = tool(
  async (
    { prompt }: { prompt: string },
    runtime: ToolRuntime<typeof GraphState.State>,
  ) => {
    //  { role: "ai", content: "Human response received: ..." }
    const resumeValue = interrupt({
      type: "human_confirmation",
      prompt, // prompt is generated by the model and surfaced to the human operator in the UI
      // Note: the assistant node always flips `initialInvocation` to false
      // before routing here, so this reads false whenever a tool call is
      // involved — it's true only for a node that runs before the assistant
      // does. Included here purely to demonstrate reading shared state.
      continuingThread: !runtime.state.initialInvocation,
    });

    // perform logic on resumeValue if needed, or just return it to the caller. The graph is paused until the human responds.

    // wait for resonse ...

    //  { role: "tool", content: "Human response received: ..." }
    return `Human response received: ${String(resumeValue)}`;
  },
  {
    name: "request_human_confirmation",
    description:
      "Pause the graph and request human input when confirmation is needed before continuing.",
    schema: {
      type: "object",
      properties: {
        prompt: {
          type: "string",
          description: "Question or prompt to ask the human before continuing",
        },
      },
      required: ["prompt"],
      additionalProperties: false,
    },
  },
);

/**
 * One Gateway tool as a LangChain tool. The model reads the spec —
 * the description and schema from the tool's contract.ts — and
 * `tools.call` sends the call it chose through the Gateway, where
 * the tool validates the arguments. A refusal is thrown, and
 * ToolNode hands its message back to the model to correct.
 */
function gatewayTool(gateway: AgentTools, spec: ModelToolSpec) {
  return tool(
    async (args: Record<string, unknown>) =>
      JSON.stringify(await gateway.call(spec.name, args)),
    {
      name: spec.name,
      description: spec.description,
      schema: { ...spec.inputSchema },
    },
  );
}

/** Every tool the assistant may call on this turn. */
function turnTools(context: GraphContextType | undefined) {
  if (!context) throw new Error("Run the graph with its context: { tools }.");
  return [
    requestHumanConfirmationTool,
    ...context.tools.specs.map((spec) => gatewayTool(context.tools, spec)),
  ];
}

/* ============================================================
 * 3. Nodes
 * ------------------------------------------------------------
 * A node is `(state, runtime) => Partial<GraphStateType>`. To add
 * a step to the pipeline — a planner, a critic, a retriever —
 * write a function here in the same shape, then wire it in step 5.
 * ============================================================ */

type GraphRuntime = Runtime<GraphContextType>;

const assistant = async (state: GraphStateType, runtime: GraphRuntime) => {
  // MODEL_PROVIDER selects the provider. Pass one explicitly -- getModel("openai"),
  // getModel("bedrock") -- to pin this node to a specific provider instead.
  const modelWithTools = (await getModel()).bindTools(turnTools(runtime.context));

  // `state.initialInvocation` is true only up to this point in the thread's
  // very first turn — flipped below so every later invocation (a follow-up
  // message, or looping back here after a tool call) reads false instead.
  const system = new SystemMessage(
    state.initialInvocation
      ? "You are a concise assistant for a starter LangGraph app. This is the start of a brand-new conversation. Keep responses short and clear. Use tools when helpful. If you need explicit user approval or missing information before continuing, call request_human_confirmation."
      : "You are a concise assistant for a starter LangGraph app. Keep responses short and clear. Use tools when helpful. If you need explicit user approval or missing information before continuing, call request_human_confirmation.",
  );

  const response = await modelWithTools.invoke([
    system,
    ...toModelMessages(state.messages),
  ]);

  return {
    messages: [response],
    initialInvocation: false,
  };
};

// Runs every tool call the assistant's last message asked for. The node is
// built per turn because the Gateway's tools arrive with the turn's context;
// it is passed the node's own runtime so interrupt() and streaming still see
// the graph.
const runTools = async (state: GraphStateType, runtime: GraphRuntime) =>
  new ToolNode(turnTools(runtime.context)).invoke(state, runtime);


/* ============================================================
 * 4. Routing
 * ------------------------------------------------------------
 * Conditional edges live here as small, testable predicates over
 * state. Add one per branch point in the graph.
 * ============================================================ */

// After the assistant runs, go to `tools` if it asked for one, otherwise finish.
function routeAfterAssistant(state: GraphStateType) {
  const last = state.messages?.[state.messages.length - 1];

  if (
    last &&
    "tool_calls" in last &&
    Array.isArray((last as AIMessage).tool_calls) &&
    (last as AIMessage).tool_calls!.length > 0
  ) {
    return "tools";
  }

  return END;
}

/* ============================================================
 * 5. Graph assembly
 * ------------------------------------------------------------
 * The checkpointer lives in this process, and AgentCore gives each
 * conversation its own session (locally, its own process), so a
 * thread lasts as long as its session: until the agent's
 * `cloud.idleSeconds` pass without a turn, or its
 * `maxLifetimeSeconds` run out. Swap MemorySaver for a durable
 * checkpointer (Postgres, DynamoDB, AgentCore Memory...) for
 * threads that outlive their session — everything else on this
 * page stays the same.
 *
 *        START
 *          │
 *          ▼
 *      assistant (access to tools) ◄───┐
 *          │                           │
 *    need a tool?                      │
 *     /        \                       │
 *    no        yes                     │
 *    │          │                      │
 *    ▼          ▼                      │
 *   END        tools ──────────────────┘
 *
 * To grow this graph: addNode(...) your new step, then point an
 * addEdge / addConditionalEdges at it. Nothing outside this block
 * needs to change.
 * ============================================================ */

const checkpointer = new MemorySaver();

/**
 * Wrap an assistant-style node so every AIMessage it returns is tagged with
 * the node's own name. Do this for each one you register below — it's what
 * makes `message.name` (visible in a `history` request) tell you which node
 * produced which reply once there's more than one in the graph. (Tool results
 * already carry this: ToolNode stamps `name: tool.name` on every ToolMessage
 * automatically, no wrapping needed there.)
 *
 * The name must be set *at construction*, not assigned after (`msg.name =
 * ...`) — the checkpointer round-trips messages through
 * serialize/deserialize on every save, using each message's original
 * constructor kwargs, so a post-construction property assignment is quietly
 * dropped the next time the thread is loaded.
 */
function withNodeName(
  name: string,
  node: (state: GraphStateType, runtime: GraphRuntime) => Promise<{ messages: BaseMessage[] }>,
) {
  return async (state: GraphStateType, runtime: GraphRuntime) => {
    const result = await node(state, runtime);
    return {
      ...result,
      messages: result.messages.map((message) =>
        message instanceof AIMessage
          ? new AIMessage({
              content: message.content,
              ...(message.tool_calls ? { tool_calls: message.tool_calls } : {}),
              ...(message.id ? { id: message.id } : {}),
              name,
              additional_kwargs: message.additional_kwargs,
              response_metadata: message.response_metadata,
            })
          : message,
      ),
    };
  };
}

export const graph = new StateGraph(GraphState, GraphContext)
  .addNode("assistant", withNodeName("assistant", assistant))
  .addNode("tools", runTools)
  .addEdge(START, "assistant")
  .addConditionalEdges("assistant", routeAfterAssistant, {
    tools: "tools",
    [END]: END,
  })
  .addEdge("tools", "assistant")
  .compile({ checkpointer });

/* ============================================================
 * 6. Public API
 * ------------------------------------------------------------
 * Everything a transport layer (index.ts, a CLI, a worker) needs
 * to drive the graph. Keep transport concerns (the agent contract,
 * auth) out of this file, and keep graph internals out of index.ts.
 * ============================================================ */

export function threadConfig(threadId: string) {
  return { configurable: { thread_id: threadId } };
}

/**
 * Thrown when a resume is asked for on a thread that isn't actually paused on
 * an `interrupt()`. Without this check the call silently no-ops — `resume`
 * targets a specific paused task, not "continue the conversation", so if
 * nothing is waiting, there's nothing to hand the value to and the graph just
 * returns its last state unchanged (looking like a repeated reply). Plain
 * follow-ups should send a message instead.
 */
export class NoPendingInterruptError extends Error {
  constructor(threadId: string) {
    super(`Thread "${threadId}" has no pending interrupt to resume.`);
    this.name = "NoPendingInterruptError";
  }
}

/** The interrupt a thread is currently paused on, if any. */
function pendingInterrupt(snapshot: StateSnapshot) {
  return snapshot.tasks.flatMap((task) => task.interrupts).at(0);
}

async function assertResumable(threadId: string): Promise<void> {
  const snapshot = await getSnapshot(threadId);
  if (!pendingInterrupt(snapshot)) throw new NoPendingInterruptError(threadId);
}

/** One run of the graph: the thread, its per-turn context, and when to stop. */
export interface Turn {
  readonly threadId: string;
  readonly context: GraphContextType;
  readonly signal?: AbortSignal;
}

/**
 * Run one turn and stream the assistant's reply token by token as it's
 * generated. Yields plain text deltas. With `resume`, `input` answers the
 * pending interrupt() rather than starting a new user message.
 */
export async function* streamAssistant(
  input: string,
  turn: Turn,
  resume?: boolean,
): AsyncGenerator<string> {
  if (resume) await assertResumable(turn.threadId);

  const options = {
    ...threadConfig(turn.threadId),
    context: turn.context,
    streamMode: "messages" as const,
    ...(turn.signal ? { signal: turn.signal } : {}),
  };
  // Resume from the last interrupt() checkpoint, or append a new user message.
  const events = resume
    ? await graph.stream(new Command({ resume: input }), options)
    : await graph.stream({ messages: [new HumanMessage(input)] }, options);

  for await (const [chunk, metadata] of events) {
    if (metadata?.langgraph_node !== "assistant") continue;
    const text = extractText(chunk.content);
    if (text) yield text;
  }
}

/** Latest checkpoint snapshot for a thread — current state plus any pending interrupt. */
export async function getSnapshot(threadId: string): Promise<StateSnapshot> {
  return graph.getState(threadConfig(threadId));
}

/** A single message, flattened into a shape that survives JSON serialization. */
export type ConversationMessage = {
  role: string;
  /** Which node produced this message — e.g. "assistant", or a tool's name. */
  name?: string;
  content: string;
  toolCalls?: { id?: string; name: string; args: Record<string, unknown> }[];
  toolCallId?: string;
};

/** What `request_human_confirmation` paused the graph to ask. */
export type PendingInterrupt = { prompt: string; continuingThread: boolean };

/** Read-only view of a thread: where it stands and everything said so far. */
export type ThreadView = {
  exists: boolean;
  interrupted: boolean;
  interrupt?: PendingInterrupt;
  /** Nodes queued to run next. Empty once the graph has reached END. */
  next: string[];
  messages: ConversationMessage[];
  updatedAt?: string;
};

/**
 * Current state of a thread, read straight from the checkpointer — no model
 * call, no graph execution, no new messages appended. Safe to poll.
 */
export async function getThread(threadId: string): Promise<ThreadView> {
  const snapshot = await getSnapshot(threadId);
  const messages: BaseMessage[] = snapshot.values?.messages ?? [];
  const interrupt = pendingInterrupt(snapshot);
  const value = interrupt?.value as PendingInterrupt | undefined;

  return {
    // A thread that was never started has no checkpoint behind it.
    exists: snapshot.createdAt !== undefined || messages.length > 0,
    interrupted: interrupt !== undefined,
    ...(value
      ? { interrupt: { prompt: value.prompt, continuingThread: value.continuingThread } }
      : {}),
    next: [...snapshot.next],
    messages: toConversation(messages),
    ...(snapshot.createdAt ? { updatedAt: snapshot.createdAt } : {}),
  };
}

/** Flatten graph messages into a transcript a client can render directly. */
export function toConversation(messages: BaseMessage[]): ConversationMessage[] {
  return messages.map((message) => {
    const entry: ConversationMessage = {
      role: message.type,
      content: extractText(message.content),
    };

    if (message.name) entry.name = message.name;

    if (message.type === "ai") {
      const toolCalls = (message as AIMessage).tool_calls;
      if (toolCalls?.length) {
        entry.toolCalls = toolCalls.map((call) => ({
          ...(call.id ? { id: call.id } : {}),
          name: call.name,
          args: call.args,
        }));
      }
    }

    if (message.type === "tool") {
      entry.toolCallId = (message as ToolMessage).tool_call_id;
    }

    return entry;
  });
}
