// The client's own manifest, generated by `npm run codegen` beside the typed
// documents it describes. Imported rather than copied so the two can never
// disagree about which operations exist.
import manifest from "../../../../../client-app/src/api/generated/persisted-documents.json";

const documents: Readonly<Record<string, string>> = manifest;

/**
 * Whether this API executes only the operations the client ships.
 *
 * Off unless the route declares GRAPHQL_PERSISTED_DOCUMENTS_ONLY: "true". On,
 * arbitrary queries are refused outright. The trade: a browser tab still
 * running an older build sends documents the new manifest may no longer list,
 * so deploy the client and this API together, and expect old tabs to need a
 * reload after an operation changes.
 */
export function persistedDocumentsOnly(): boolean {
  return process.env.GRAPHQL_PERSISTED_DOCUMENTS_ONLY === "true";
}

/**
 * The request body to execute: the manifest's copy of the document the
 * request names by hash, never the text it sent. `null` when it names none.
 */
export function resolvePersistedDocument(body: string | undefined): string | null {
  let params: {
    extensions?: { persistedQuery?: { sha256Hash?: unknown } };
  } & Record<string, unknown>;
  try {
    params = JSON.parse(body ?? "");
  } catch {
    return null;
  }
  const hash = params.extensions?.persistedQuery?.sha256Hash;
  const document =
    typeof hash === "string" ? documents[`sha256:${hash}`] : undefined;
  return document === undefined
    ? null
    : JSON.stringify({ ...params, query: document });
}
